### PR TITLE
Feat/rel notes3

### PR DESCRIPTION
**Pull request by fkr**

### CODE REVIEW

**Comment by fkr** [comment]
final merge of RelNotes3

**Review by garloff — COMMENTED** [review]
Have we merged an old version of a branch before?
Somehow strange ...
I will double check the list of commits in feat/RelNotes3 now ...

**Comment by fkr** [comment]
@garloff thats what I just did. I merged main onto RelNotes3, removed all conflicts with the version of main and pushed.

**Comment by garloff** [comment]
> @garloff thats what I just did. I merged main onto RelNotes3, removed all conflicts with the version of main and pushed.

AH, OK, thanks. No point in doing double work then ...

**Review by garloff — APPROVED** [review]
/lgtm

**Pull request merged**
