### PR TITLE
Remove link to CoC committee as site doesn't exist yet

### PR DESCRIPTION
**Pull request by itrich**
As hinted out by @ManuelaUr, the link to the CoC committee isn't available yet. We should remove this link until we have a corresponding site on our homepage.

### CODE REVIEW

**Review by fkr — COMMENTED** [review]
How/where do I contact the committee?

**Comment by itrich** [comment]
We don't have a committee and actually there was no feedback to my call for participation at all. :man_shrugging:

**Comment by fkr** [comment]
> We don't have a committee and actually there was no feedback to my call for participation at all. 🤷‍♂️

Would it make sense to rephrase the sentence then to 'you may contact the SCS project team at project AT ...' ?

**Comment by itrich** [comment]
> > We don't have a committee and actually there was no feedback to my call for participation at all. man_shrugging
> 
> Would it make sense to rephrase the sentence then to 'you may contact the SCS project team at project AT ...' ?

Sure, absolutely!

**Review by fkr — APPROVED** [review]
LGTM. Thanks for the corrections.

**Pull request merged**
