### PR TITLE
More content for the cluster improvements.

### PR DESCRIPTION
**Pull request by garloff**
With specific links.

Signed-off-by: Kurt Garloff <kurt@garloff.de>

### CODE REVIEW

**Review by fkr — COMMENTED** [review]
I'd like to suggest a tad different wording and will push a suggestion.

**Comment by fkr** [comment]
Pushed.

**Comment by garloff** [comment]
Note that the link to the upgrade guide still points to Nirvana until we have
https://github.com/SovereignCloudStack/k8s-cluster-api-provider/pull/293
merged. (I've asked Sven for a sanity check.)

**Review by garloff — COMMENTED** [review]
This is better, thanks!

**Comment by garloff** [comment]
Formally, this still needs an approve ...

**Pull request merged**
