### PR TITLE
Added initial documentation about example setup

### PR DESCRIPTION
**Pull request by JuanPTM**
initial version of the example setup description

### CODE REVIEW

**Comment by reqa** [comment]
Please add these points:
* What does this describe? A link to the playbook/task would probably be good?
* Motivation: For which purpose is this interesting? Mention the SCS persona that is the target of this documentation (see https://github.com/SovereignCloudStack/standards/blob/773646d1d6af19b151b21e6b706c946e8169c07d/GLOSSARY.md#personas)

**Comment by garloff** [comment]
Much better now.
Where on the docs page should this go?

**Comment by JuanPTM** [comment]
> Much better now. Where on the docs page should this go?

I don't know, maybe @maxwolfs can help us here

**Comment by maxwolfs** [comment]
> Example federation setup (testbed)

I would put it in IAM/Guides/Example federation setup (testbed) next to Domain Manager setup and usage.

Then it has to be added in the sidebar here: https://github.com/SovereignCloudStack/docs/blob/main/sidebarsDocs.js#L357

**Comment by JuanPTM** [comment]
> > Example federation setup (testbed)
> 
> I would put it in IAM/Guides/Example federation setup (testbed) next to Domain Manager setup and usage.
> 
> Then it has to be added in the sidebar here: https://github.com/SovereignCloudStack/docs/blob/main/sidebarsDocs.js#L357

Sidebar file changed and original file moved to the correct location, 

how is it looking now

**Comment by maxwolfs** [comment]
Could you please work on a local branch within the main repository instead of using a fork? Then the build will work and this will also allow us to review the changes on the rendered staging branch directly on https://docs-staging.scs.community/

**Comment by JuanPTM** [comment]
I've created another MR using a local branch instead of a fork. 

https://github.com/SovereignCloudStack/docs/pull/202

**Pull request closed without merging**
