### PR TITLE
Disscussion about OVN Feature Matrix

### PR DESCRIPTION
**Pull request by matfechner**
Signed-off-by: Mathias Fechner <mathias.fechner@plusserver.com>

@osfrickler
@fkr 

Please take a  look

### CODE REVIEW

**Comment by fkr** [comment]
Discussed with @osfrickler. The matrix should have more details, be more verbose on certain topics (IPv6 was an example).
Best to be discussed between @matfechner and @osfrickler next week.

**Comment by fkr** [comment]
Imho this can be merged and be worked on through further PRs if need be.

**Comment by berendt** [comment]
We are working with the Github Reviews feature on our end. I think we should do that here as well. Then you can see directly in the dashboard where you should look at something.

But it looks like neither Mathias nor Jens are in the SCS Org. At least I can't assign them.

**Review by fkr — APPROVED** [review]
LGTM!

**Pull request merged**
