### PR TITLE
Remove twitter from community page

### PR DESCRIPTION
**Pull request by jschoone**

### CODE REVIEW

**Review by maxwolfs — APPROVED** [review]

**Comment by FriederikeZelke** [comment]
Was the Twitter/X Channel also deleted?

**Comment by berendt** [comment]
@FriederikeZelke The channel is still there: https://twitter.com/scs_osballiance. Should be removed to avoid confusions.

**Comment by jschoone** [comment]
> @FriederikeZelke The channel is still there: https://twitter.com/scs_osballiance. Should be removed to avoid confusions.

Yes thanks. We're already on it.
The PRs focus on the no longer existing bird.

**Review by FriederikeZelke — COMMENTED** [review]
LGTM. Thanks.

**Pull request merged**
