### PR TITLE
Feat: Add status page docs

### PR DESCRIPTION
**Pull request by joshuai96**
Adding the missing docs about all parts the status page.

Closes: SovereignCloudStack/issues#610

### CODE REVIEW

**Comment by joshuai96** [comment]
Maybe the docs from `status-page-openapi` and `status-page-api` should be more separated from each other to make it clearer that `status-page-openapi` is more conceptual and `status-page-api` is just one possibility to implement these concepts. Maybe categories like `Concepts` and `API`.

**Comment by joshuai96** [comment]
`overview` for `status-page-deployment` is not in line with the guidelines, as it's only a overview diagram of the deployment. I would like to write a little more to be inline with the general guidelines.

In general some improvements should be made to all the docs to adhere to the guidelines.

**Comment by joshuai96** [comment]
@fkr @maxwolfs is there a default for document ids? They generate from the filename. Some use `-` others `_` to separate words in the filename. Docusaurus does not seem to care, and either is fine.

**Comment by maxwolfs** [comment]
> @fkr @maxwolfs is there a default for document ids? They generate from the filename. Some use `-` others `_` to separate words in the filename. Docusaurus does not seem to care, and either is fine.

I would prefer to use `-` but either way is fine.

**Comment by joshuai96** [comment]
@maxwolfs I don't seem to get the build working. Locally I don't get that error, when starting the development server. Any idea?

**Comment by maxwolfs** [comment]
> @maxwolfs I don't seem to get the build working. Locally I don't get that error, when starting the development server. Any idea?

Have a look at the build logs and you can see why it breaks:
https://github.com/SovereignCloudStack/docs/actions/runs/9675459607/job/26694377986

There is a broken link on the /docs index page, that prevents the build. You can also run the build locally with `npm run build` to test it locally, which produces the same error:


```
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:53:19)
    at async /Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:64:9
    at async mapAsyncSequential (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
    at async Command.build (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:62:5) {
  [cause]: Error: Docusaurus found broken links!
  
  Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
  Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
  
  Exhaustive list of all broken links found:
  - Broken link on source page path = /docs/:
     -> linking to /docs/operating-scs/components/status-page/docs/overview
  
      at throwError (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/logger/lib/index.js:79:11)
      at reportBrokenLinks (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/server/brokenLinks.js:242:47)
      at handleBrokenLinks (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/server/brokenLinks.js:274:5)
      at executeBrokenLinksCheck (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:182:47)
      at /Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:136:66
      at Object.async (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/utils.js:36:47)
      at buildLocale (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:136:30)
      at async tryToBuildLocale (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:46:13)
      at async /Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:64:9
      at async mapAsyncSequential (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
      at async Command.build (/Users/maxwolfs/dev/docs/node_modules/@docusaurus/core/lib/commands/build.js:62:5)
}
```

If you have a look at the https://docs.scs.community/docs page you see that the Architectual Overview has a component `Status Page` linking to its docs with the url `https://docs.scs.community/docs/operating-scs/components/status-page/docs/overview` which is not working properly with the updated docs within this branch. 

Solution is to update the link to updated docs in the `static/data/architecturalOverviewData.json` https://github.com/SovereignCloudStack/docs/blob/e531374601993621f42d1309b77466dca3892b6c/static/data/architecturalOverviewData.json#L11

When checking out this branch it seems that the new correct link seems to be: `http://localhost:3000/docs/operating-scs/components/status-page-openapi/docs/overview`

**Comment by maxwolfs** [comment]
Hey @joshuai96, what's the current state here? Is this ready for review?

**Comment by joshuai96** [comment]
@maxwolfs mostly blocked by SovereignCloudStack/status-page-web/pull/19

We could skip that, merge this and create a second PR.

**Comment by joshuai96** [comment]
SovereignCloudStack/status-page-web#19 will be excluded

**Comment by joshuai96** [comment]
@maxwolfs Ready to review

**Pull request merged**
