### PR TITLE
Add Container Introduction

### LINKED ISSUE #95: Prepare Container layer introduction
Result from SIG Documentation

* We need an introduction text for container layer answering the following questions on: https://docs.scs.community/docs/category/container-layer
    * Who is the target group? 
    * What is it not?
    * Prerequisites and Requirements (knowledge, software, hardware)
    * Features, Capabilities and Limitations (k8s cluster api provider only runs on openstack)
        * how does it interact with the iaas layer?
    * current plans on implementations, roadmap and current state on clusterstacks 
        * is it worth it to implement with the outlook on clusterstacks?
        * comparison table of cluster-api-provider and cluster-stacks
        * alpha label might make sense for cluster-stacks to indicate that it's in development
    * Success Stories and Deployment Examples

https://input.scs.community/container-layer-intro-on-docs-page?edit

### PR DESCRIPTION
**Pull request by maxwolfs**
written by @fdobrovolny – Thanks!

As discussed in the SIG Docs, adding some more information of the upcoming cluster-stacks would be great.

closes #95

### CODE REVIEW

**Comment by fdobrovolny** [comment]
@SovereignCloudStack/syself could someone from you guys please add some section and information about clusterstacks? Maybe some comparison of the two?

**Comment by berendt** [comment]
Does it makes sense to add a "Vision" section as well? Not sure if the @fdobrovolny  can write this, more like an idea for this kind of document.

**Comment by fdobrovolny** [comment]
@berendt 
> Does it makes sense to add a "Vision" section as well? Not sure if the @fdobrovolny can write this, more like an idea for this kind of document.

Could you explain more about how you mean it?
Do you mean vision as a kind of road map or more like an ultimate end-goal of a perfect solution, or more like philosophical what values should it have and what should it enable its users to do?

**Comment by berendt** [comment]
The idea would be to describe where we see the container layer in 18 months. But let's maybe better take that separately and add to it later.

**Comment by janiskemper** [comment]
I can add something @fdobrovolny but I'm not sure how you mean it. Do you want to include that information also in this PR or another one that I can work  on after this is merged?

**Review by fdobrovolny — APPROVED** [review]

**Comment by fdobrovolny** [comment]
@janiskemper I discussed this with @maxwolfs, and we will merge this. Could you please make a new PR extending this?

**Comment by janiskemper** [comment]
Here is the issue: https://github.com/SovereignCloudStack/docs/issues/99

**Pull request merged**
