### PR TITLE
Add color coding to the to standards table in the docs page

### PR DESCRIPTION
**Pull request by cah-patrickthiem**
Added the color mapping with a react component. Needed to change the overview.md file to .mdx format.

related issue: [445](https://github.com/SovereignCloudStack/standards/issues/445)

### CODE REVIEW

**Comment by cah-patrickthiem** [comment]
Regarding colors and high contrast ratio:
I did use a [contrast checker](https://webaim.org/resources/contrastchecker/) to pick the colors in contrast especially to the link color. I always made sure "WCAG AA" was met in normal text.
To be sure the colors match each other I used "HSL" ratio in the color picker.

The colors I picked are all relatively light pastel colors:
red: deprecated
yellow: draft
green: stable
blue: effective

However, if you wish other colors, please give feedback. Also the stable and effective colors could be swapped imo.

**Comment by cah-patrickthiem** [comment]
looks like this:
image

**Review by mbuechse — COMMENTED** [review]
Good work! I would like to build something based on this, and I think 95 % of your work can be used for that. I have the following desiderata:

- I have the impression that the colors are being set using plain JavaScript. So I would try to not use React, but onload or something.
- I absolutely hate that the whole `populateStds.js` has been reformatted. I would like to keep reformatting and semantic change separate (using separate PRs). But I don't even see the need for the reformatting.

**Comment by cah-patrickthiem** [comment]
> Good work! I would like to build something based on this, and I think 95 % of your work can be used for that. I have the following desiderata:
> 
> * I have the impression that the colors are being set using plain JavaScript. So I would try to not use React, but onload or something.
> * I absolutely hate that the whole `populateStds.js` has been reformatted. I would like to keep reformatting and semantic change separate (using separate PRs). But I don't even see the need for the reformatting.

Regarding react: I used react here, because the docusaurus documentation says that if you want to enrich markdown with more features (e.g. coloring), use react: see [here](https://tutorial.docusaurus.io/docs/tutorial-basics/markdown-features/#links:~:text=MDX%20can%20make%20your%20documentation%20more%20interactive%20and%20allows%20using%20any%20React%20components%20inside%20Markdown%3A)
In general it is plain js code, but in order to be parsed by docusaurus, we need that little react "useEffect" function there. Besides that, no further react stuff is used. I tested it also with <script> tags, but that did not work. 
If you have another idea I am not aware of, let me know.

Second, the reformatting was somehow done automatically, I'll try to figure out why and reverse it.

**Comment by mbuechse** [comment]
I probably won't become a fan of Docusaurus, but so be it. Thanks for the explanation!

**Review by mbuechse — APPROVED** [review]
LGTM. Just one minor thing: dark mode. Maybe we can postpone dark mode. If you can address it right away, all the better.

**Comment by cah-patrickthiem** [comment]
> LGTM. Just one minor thing: dark mode. Maybe we can postpone dark mode. If you can address it right away, all the better.

Well, I think the colors also work in dark mode, at least regarding the signaling purpose, for sure the colors do not match the dark background in an esthetic way.

I would need to investigate on how to implement this.

Here is a screenshot in dark mode. If that is ok for you right now, we can merge it for now imo. Let me know what you prefer.
image

**Comment by mbuechse** [comment]
I have already approved it, noting that we can postpone dark mode. Go ahead!

**Pull request merged**
