### PR TITLE
Feat/read mand flavors

### PR DESCRIPTION
**Pull request by garloff**
This implements https://github.com/SovereignCloudStack/issues/issues/235

### CODE REVIEW

**Comment by garloff** [comment]
Once #163 has landed, we should merge this against main.

**Comment by garloff** [comment]
And this fixes #162

**Comment by tibeer** [comment]
@garloff according to https://peps.python.org/pep-0257/ function descriptions should always be in triple quotes. Will look into this again once conflicts are resolved.

**Comment by garloff** [comment]
@tibeer: I think we should build a simple pylint CI action requiring 9+/10 points or so ...

**Comment by garloff** [comment]
Superceded by PR #183 (rebased).

**Pull request closed without merging**
